/**
 * Translation catalogs for the Prompt History plugin, registered through
 * `registry.registerTranslations`. Every locale carries the same flat key
 * set; the host requires an English fallback and validates the key shape,
 * message count, and message length at registration.
 *
 * Keys are flat (`^[a-z][a-zA-Z0-9_-]*$`) and match the parity reference's
 * user-facing copy in the apps/web/src/locales task.json catalogs (the promptHistory*
 * row labels, expand/collapse, duration units, and the panel states). The
 * stack keys (`expandAgentPrompts`, `collapseAgentPrompts`,
 * `agentPromptStackLabel`) are this plugin's own: the core panel has no
 * folding, so `display_6_agent_prompt_display: collapse` needs copy the reference
 * never carried.
 */
export const CATALOGS = {
  en: {
    panelTitle: "Prompt History",
    promptHistoryPromptLabel: "Prompt {{number}}",
    promptHistoryPromptLabelGeneric: "Prompt",
    expandPrompt: "Expand prompt",
    collapsePrompt: "Collapse prompt",
    expandAgentPrompts: "Expand {{count}} agent prompts",
    collapseAgentPrompts: "Collapse {{count}} agent prompts",
    agentPromptStackLabel: "{{count}} agent prompts",
    durationUnitSeconds: "s",
    durationUnitMinutes: "m",
    durationUnitHours: "h",
    durationUnitDays: "d",
    promptAgeJustNow: "just now",
    promptHistoryEmpty: "No prompts yet.",
    loading: "Loading...",
    loadingOlderMessages: "Loading older messages...",
    error: "Error",
    retry: "Retry",
  },
  "pt-pt": {
    panelTitle: "Histórico de prompts",
    promptHistoryPromptLabel: "Prompt {{number}}",
    promptHistoryPromptLabelGeneric: "Prompt",
    expandPrompt: "Expandir prompt",
    collapsePrompt: "Recolher prompt",
    expandAgentPrompts: "Expandir {{count}} prompts do agente",
    collapseAgentPrompts: "Recolher {{count}} prompts do agente",
    agentPromptStackLabel: "{{count}} prompts do agente",
    durationUnitSeconds: "s",
    durationUnitMinutes: "m",
    durationUnitHours: "h",
    durationUnitDays: "d",
    promptAgeJustNow: "agora mesmo",
    promptHistoryEmpty: "Ainda sem prompts.",
    loading: "A carregar...",
    loadingOlderMessages: "A carregar mensagens mais antigas...",
    error: "Erro",
    retry: "Tentar novamente",
  },
  "zh-cn": {
    panelTitle: "提示历史",
    promptHistoryPromptLabel: "提示 {{number}}",
    promptHistoryPromptLabelGeneric: "提示",
    expandPrompt: "展开提示",
    collapsePrompt: "收起提示",
    expandAgentPrompts: "展开 {{count}} 条代理提示",
    collapseAgentPrompts: "收起 {{count}} 条代理提示",
    agentPromptStackLabel: "{{count}} 条代理提示",
    durationUnitSeconds: "秒",
    durationUnitMinutes: "分",
    durationUnitHours: "时",
    durationUnitDays: "天",
    promptAgeJustNow: "刚刚",
    promptHistoryEmpty: "暂无提示。",
    loading: "加载中…",
    loadingOlderMessages: "正在加载更早的消息…",
    error: "错误",
    retry: "重试",
  },
  "zh-hk": {
    panelTitle: "提示歷史",
    promptHistoryPromptLabel: "提示 {{number}}",
    promptHistoryPromptLabelGeneric: "提示",
    expandPrompt: "展開提示",
    collapsePrompt: "收起提示",
    expandAgentPrompts: "展開 {{count}} 條代理提示",
    collapseAgentPrompts: "收起 {{count}} 條代理提示",
    agentPromptStackLabel: "{{count}} 條代理提示",
    durationUnitSeconds: "秒",
    durationUnitMinutes: "分",
    durationUnitHours: "時",
    durationUnitDays: "天",
    promptAgeJustNow: "剛剛",
    promptHistoryEmpty: "暫無提示。",
    loading: "載入中…",
    loadingOlderMessages: "正在載入更早的訊息…",
    error: "錯誤",
    retry: "重試",
  },
  "zh-tw": {
    panelTitle: "提示歷史",
    promptHistoryPromptLabel: "提示 {{number}}",
    promptHistoryPromptLabelGeneric: "提示",
    expandPrompt: "展開提示",
    collapsePrompt: "收起提示",
    expandAgentPrompts: "展開 {{count}} 條代理提示",
    collapseAgentPrompts: "收起 {{count}} 條代理提示",
    agentPromptStackLabel: "{{count}} 條代理提示",
    durationUnitSeconds: "秒",
    durationUnitMinutes: "分",
    durationUnitHours: "時",
    durationUnitDays: "天",
    promptAgeJustNow: "剛剛",
    promptHistoryEmpty: "暫無提示。",
    loading: "載入中…",
    loadingOlderMessages: "正在載入更早的訊息…",
    error: "錯誤",
    retry: "重試",
  },
  pseudo: {
    panelTitle: "Ƥŕōḿƥţ Ħįşţōŕŷ",
    promptHistoryPromptLabel: "Ƥŕōḿƥţ {{number}}",
    promptHistoryPromptLabelGeneric: "Ƥŕōḿƥţ",
    expandPrompt: "Ēxƥàńď ƥŕōḿƥţ",
    collapsePrompt: "Ćōĺĺàƥśē ƥŕōḿƥţ",
    expandAgentPrompts: "Ēxƥàńď {{count}} àĝēńţ ƥŕōḿƥţś",
    collapseAgentPrompts: "Ćōĺĺàƥśē {{count}} àĝēńţ ƥŕōḿƥţś",
    agentPromptStackLabel: "{{count}} àĝēńţ ƥŕōḿƥţś",
    durationUnitSeconds: "ś",
    durationUnitMinutes: "ḿ",
    durationUnitHours: "ĥ",
    durationUnitDays: "ď",
    promptAgeJustNow: "ĵũśţ ńōŵ",
    promptHistoryEmpty: "Ńō ƥŕōḿƥţś ŷēţ.",
    loading: "Ĺōàďĩńĝ...",
    loadingOlderMessages: "Ĺōàďĩńĝ ōĺďēŕ ḿēśśàĝēś...",
    error: "Ēŕŕōŕ",
    retry: "Ŕēţŕŷ",
  },
};
