/**
 * Translation catalogs for the Prompt History plugin, registered through
 * `registry.registerTranslations`. Every locale carries the same flat key
 * set; the host requires an English fallback and validates the key shape,
 * message count, and message length at registration.
 *
 * Keys are flat (`^[a-z][a-zA-Z0-9_-]*$`) and match the parity reference's
 * user-facing copy in the apps/web/src/locales task.json catalogs (the promptHistory*
 * row labels, expand/collapse, duration units, and the panel states).
 */
export const CATALOGS = {
  en: {
    panelTitle: "Prompt History",
    promptHistoryPromptLabel: "Prompt {{number}}",
    promptHistoryPromptLabelGeneric: "Prompt",
    expandPrompt: "Expand prompt",
    collapsePrompt: "Collapse prompt",
    durationUnitSeconds: "s",
    durationUnitMinutes: "m",
    durationUnitHours: "h",
    promptHistoryEmpty: "No prompts yet.",
    loading: "Loading...",
    loadingOlderMessages: "Loading older messages...",
    error: "Error",
    retry: "Retry",
  },
  "pt-pt": {
    panelTitle: "Histórico de prompts",
    promptHistoryPromptLabel: "Prompt {{number}}",
    promptHistoryPromptLabelGeneric: "Prompt",
    expandPrompt: "Expandir prompt",
    collapsePrompt: "Recolher prompt",
    durationUnitSeconds: "s",
    durationUnitMinutes: "m",
    durationUnitHours: "h",
    promptHistoryEmpty: "Ainda sem prompts.",
    loading: "A carregar...",
    loadingOlderMessages: "A carregar mensagens mais antigas...",
    error: "Erro",
    retry: "Tentar novamente",
  },
  "zh-cn": {
    panelTitle: "提示历史",
    promptHistoryPromptLabel: "提示 {{number}}",
    promptHistoryPromptLabelGeneric: "提示",
    expandPrompt: "展开提示",
    collapsePrompt: "收起提示",
    durationUnitSeconds: "秒",
    durationUnitMinutes: "分",
    durationUnitHours: "时",
    promptHistoryEmpty: "暂无提示。",
    loading: "加载中…",
    loadingOlderMessages: "正在加载更早的消息…",
    error: "错误",
    retry: "重试",
  },
  "zh-hk": {
    panelTitle: "提示歷史",
    promptHistoryPromptLabel: "提示 {{number}}",
    promptHistoryPromptLabelGeneric: "提示",
    expandPrompt: "展開提示",
    collapsePrompt: "收起提示",
    durationUnitSeconds: "秒",
    durationUnitMinutes: "分",
    durationUnitHours: "時",
    promptHistoryEmpty: "暫無提示。",
    loading: "載入中…",
    loadingOlderMessages: "正在載入更早的訊息…",
    error: "錯誤",
    retry: "重試",
  },
  "zh-tw": {
    panelTitle: "提示歷史",
    promptHistoryPromptLabel: "提示 {{number}}",
    promptHistoryPromptLabelGeneric: "提示",
    expandPrompt: "展開提示",
    collapsePrompt: "收起提示",
    durationUnitSeconds: "秒",
    durationUnitMinutes: "分",
    durationUnitHours: "時",
    promptHistoryEmpty: "暫無提示。",
    loading: "載入中…",
    loadingOlderMessages: "正在載入更早的訊息…",
    error: "錯誤",
    retry: "重試",
  },
  pseudo: {
    panelTitle: "Ƥŕōḿƥţ Ħįşţōŕŷ",
    promptHistoryPromptLabel: "Ƥŕōḿƥţ {{number}}",
    promptHistoryPromptLabelGeneric: "Ƥŕōḿƥţ",
    expandPrompt: "Ēxƥàńď ƥŕōḿƥţ",
    collapsePrompt: "Ćōĺĺàƥśē ƥŕōḿƥţ",
    durationUnitSeconds: "ś",
    durationUnitMinutes: "ḿ",
    durationUnitHours: "ĥ",
    promptHistoryEmpty: "Ńō ƥŕōḿƥţś ŷēţ.",
    loading: "Ĺōàďĩńĝ...",
    loadingOlderMessages: "Ĺōàďĩńĝ ōĺďēŕ ḿēśśàĝēś...",
    error: "Ēŕŕōŕ",
    retry: "Ŕēţŕŷ",
  },
};
